-- ==========================================================
-- Migration 004: Notes Schema Enhancement, Realtime & Storage
-- ==========================================================

-- 1. Ensure Notes Table with JSONB Support for Rich Blocks, Attachments, and Links
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    category TEXT DEFAULT '',
    blocks JSONB NOT NULL DEFAULT '[]'::jsonb,
    attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
    links JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- If the table already existed without blocks, attachments, or links, add them safely
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'notes' AND column_name = 'blocks') THEN
        ALTER TABLE public.notes ADD COLUMN blocks JSONB NOT NULL DEFAULT '[]'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'notes' AND column_name = 'attachments') THEN
        ALTER TABLE public.notes ADD COLUMN attachments JSONB NOT NULL DEFAULT '[]'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'notes' AND column_name = 'links') THEN
        ALTER TABLE public.notes ADD COLUMN links JSONB NOT NULL DEFAULT '[]'::jsonb;
    END IF;
END $$;

-- 2. Index for fast lookup by user
CREATE INDEX IF NOT EXISTS idx_notes_user_id ON public.notes(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_updated_at ON public.notes(updated_at DESC);

-- 3. Row Level Security (RLS)
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own notes" ON public.notes;
CREATE POLICY "Users can view their own notes"
    ON public.notes FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own notes" ON public.notes;
CREATE POLICY "Users can insert their own notes"
    ON public.notes FOR INSERT
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own notes" ON public.notes;
CREATE POLICY "Users can update their own notes"
    ON public.notes FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own notes" ON public.notes;
CREATE POLICY "Users can delete their own notes"
    ON public.notes FOR DELETE
    USING (auth.uid() = user_id);

-- 4. Enable Supabase Realtime for notes table
ALTER PUBLICATION supabase_realtime ADD TABLE public.notes;

-- 5. Storage Bucket Configuration for Note Attachments
INSERT INTO storage.buckets (id, name, public)
VALUES ('note-attachments', 'note-attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for note-attachments
DROP POLICY IF EXISTS "Allow authenticated users to upload note attachments" ON storage.objects;
CREATE POLICY "Allow authenticated users to upload note attachments"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'note-attachments' AND auth.uid()::text = (storage.foldername(name))[1]);

DROP POLICY IF EXISTS "Allow public read access to note attachments" ON storage.objects;
CREATE POLICY "Allow public read access to note attachments"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'note-attachments');

DROP POLICY IF EXISTS "Allow users to delete their own note attachments" ON storage.objects;
CREATE POLICY "Allow users to delete their own note attachments"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (bucket_id = 'note-attachments' AND auth.uid()::text = (storage.foldername(name))[1]);
